-- Auto-generated by scripts/importRecipes.ts
-- Generated at: 2026-02-27T20:42:55.038Z

-- recipe_id: 15
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'port ris eller annat gryn',
  4,
  NULL,
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'falukorv eller kycklingstekkorv',
  550,
  'g',
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'gul lök',
  1,
  NULL,
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'olja',
  1,
  'msk',
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'tomatpuré',
  3,
  'msk',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'matlagningsgrädde',
  2.5,
  'dl',
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'mjölk',
  1,
  'dl',
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'japansk soja',
  1,
  'msk',
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'dijonsenap',
  1,
  'tsk',
  false,
  9,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'peppar',
  NULL,
  NULL,
  false,
  10,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'salt',
  NULL,
  NULL,
  false,
  11,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  'grovskuren vitkål med persilja',
  NULL,
  NULL,
  false,
  12,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  1,
  'Koka riset enligt anvisningen på förpackningen.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  2,
  'Skär korven i stavar. Skala och hacka löken.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  3,
  'Stek korv och lök i oljan i en stekpanna ca 5 minuter. Tillsätt tomatpuré och fräs någon minut.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  4,
  'Rör ner grädde, mjölk, soja och dijonsenap. Låt sjuda ca 5 minuter.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  5,
  'Smaka av med peppar och ev salt.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  15,
  6,
  'Till servering: Servera korvstroganoffen med ris och gärna vitkålssallad eller en sallad med tomat och gurka.',
  now()
);

-- recipe_id: 16
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'kycklingfiléer (à ca 150 g)',
  4,
  NULL,
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'olja',
  1,
  'tsk',
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'salt',
  0.5,
  'tsk',
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'peppar',
  1,
  'krm',
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'tärnat bacon',
  140,
  'g',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'banan',
  1,
  NULL,
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'matlagningsgrädde',
  2.5,
  'dl',
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'chilisås',
  1,
  'dl',
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'port ris eller couscous',
  4,
  NULL,
  false,
  9,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'saltade jordnötter',
  1,
  'dl',
  false,
  10,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  'sallad',
  NULL,
  NULL,
  false,
  11,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  1,
  'Sätt ugnen på 225°C.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  2,
  'Skär kycklingen i strimlor och bryn den i oljan i en stekpanna i omgångar, krydda med salt och peppar. Lägg i en ugnssäker form. Stek baconet och lägg på kycklingen.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  3,
  'Skala och skiva bananen och lägg dem på kycklingen.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  4,
  'Rör ihop grädde och chilisås, smaka av med salt och peppar. Häll det över kycklingen.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  5,
  'Tillaga mitt i ugnen ca 20 minuter.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  6,
  'Koka riset enligt anvisningen på förpackningen.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  16,
  7,
  'Strö jordnötterna över kycklingen och servera med riset.',
  now()
);

-- recipe_id: 17
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'gula lökar',
  2,
  NULL,
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'vitlöksklyftor',
  2,
  NULL,
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'nötfärs eller hushållsfärs (ärt- och nötfärs)',
  500,
  'g',
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'olja',
  1,
  'msk',
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'tomatpuré',
  4,
  'msk',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'torkad timjan',
  1,
  'tsk',
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'torkad rosmarin',
  1,
  'tsk',
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'krossade tomater (à 390 g)',
  1,
  'förp',
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'köttbuljongtärning',
  1,
  NULL,
  false,
  9,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'salt',
  NULL,
  NULL,
  false,
  10,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'peppar',
  NULL,
  NULL,
  false,
  11,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'smör (6 msk motsvarar ca 90 g)',
  6,
  'msk',
  false,
  12,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'vetemjöl',
  6,
  'msk',
  false,
  13,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'mjölk',
  10,
  'dl',
  false,
  14,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'riven parmesan',
  2,
  'dl',
  false,
  15,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'torkade lasagneplattor',
  9,
  NULL,
  false,
  16,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  'sallad',
  NULL,
  NULL,
  false,
  17,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  1,
  'Sätt ugnen på 175°C.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  2,
  'Köttfärssås: Skala och hacka lök och vitlök. Fräs färs, lök och vitlök i oljan i en stekpanna.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  3,
  'Tillsätt tomatpuré som får fräsa med i färsen någon minut. Krydda med timjan och rosmarin. Tillsätt krossade tomater och buljongtärning låt det koka ca 10 minuter. Smaka av med salt och peppar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  4,
  'Ostsås: Smält smöret och vispa ner mjölet. Häll i lite av mjölken i taget under vispning. Koka upp och låt såsen koka ca 5 minuter, rör då och då. Rör ner parmesanosten och smaka av med salt och peppar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  5,
  'Häll lite ostsås i botten på en ugnssäker form (ca 20 x 30 cm). Lägg på ett lager lasagneplattor och sen ett lager köttfärssås. Upprepa stegen och avsluta med ett lager ostsås.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  6,
  'Sätt in lasagnen mitt i ugnen ca 40 minuter (eller tiden enligt förpackningen på lasagneplattorna.)',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  17,
  7,
  'Till servering: Servera lasagnen med en enkel sallad.',
  now()
);

-- recipe_id: 18
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'vetemjöl',
  2,
  'dl',
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'mjölk',
  4,
  'dl',
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'ägg',
  2,
  NULL,
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'salt',
  0.5,
  'tsk',
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'fast potatis',
  900,
  'g',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'ca 375 g skivat rimmat sidfläsk eller stekfläsk',
  NULL,
  NULL,
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'smör eller margarin',
  2,
  'msk',
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'morötter',
  3,
  NULL,
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  'lingonsylt',
  NULL,
  NULL,
  false,
  9,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  1,
  'Sätt ugnen på 125°C och sätt in en plåt.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  2,
  'Raggmunk: Vispa mjölet med hälften av mjölken till en slät smet i en bunke. Vispa ner resten av mjölken, äggen och saltet.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  3,
  'Skala och riv potatisen grovt. Krama ur vätskan och vänd ner den i smeten genast så att den inte mörknar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  4,
  'Strimla och stek fläsket krispigt i en stekpanna. Lägg det på plåten i ugnen och håll det varmt.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  5,
  'Hetta upp lite av matfettet i en stekpanna och klicka ner smeten och stek raggmunkarna i omgångar. Håll dem varma på plåten i ugnen.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  6,
  'Skala morötterna och skär i stavar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  18,
  7,
  'Till servering: Servera fläsket med raggmunkar, morötter och lingonsylt.',
  now()
);

-- recipe_id: 19
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  'pancetta eller guanciale',
  200,
  'g',
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  'vitlöksklyfta',
  1,
  NULL,
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  'ägg',
  3,
  NULL,
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  'finriven pecorinoost',
  2,
  'dl',
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  'finriven parmesan (+ ev extra till servering)',
  2,
  'dl',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  'spaghetti eller linguine',
  400,
  'g',
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  'svartpeppar',
  NULL,
  NULL,
  false,
  7,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  1,
  'Skär pancettan i cm-stora tärningar. Skala och hacka vitlöken. Stek pancettan och vitlöken knaprig i en stor stekpanna.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  2,
  'Vispa ihop äggen och blanda med både parmesan och pecorinoosten.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  3,
  'Koka pastan enligt anvisning på förpackningen. Häll av men spara ca 1 dl av pastavattnet (för 4 port).',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  19,
  4,
  'Sänk värmen och lägg pastan i stekpannan med pancettan och vänd runt. Häll över ost- och äggsmeten samt pastavattnet. Rör runt på svag värme till en krämig pasta. Strö över svartpeppar och gärna extra parmesan.',
  now()
);

-- recipe_id: 20
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'gul lök',
  1,
  NULL,
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'vitlöksklyftor',
  2,
  NULL,
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'champinjoner',
  250,
  'g',
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'kokta kikärtor (à 380 g)',
  1,
  'förp',
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'olja',
  2,
  'msk',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'tomatpuré',
  1,
  'msk',
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'grönsaksbuljong',
  1,
  NULL,
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'konserverade körsbärstomater (à ca 400 g)',
  1,
  'förp',
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'vatten',
  7,
  'dl',
  false,
  9,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  '- 3 dl visp- eller matlagningsgrädde',
  2.5,
  NULL,
  false,
  10,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'torkad basilika',
  1,
  'msk',
  false,
  11,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'torkad timjan',
  0.5,
  'msk',
  false,
  12,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  '- 1 tsk chiliflakes',
  0.5,
  NULL,
  false,
  13,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'salt',
  1.5,
  'tsk',
  false,
  14,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'svartpeppar',
  0.5,
  'tsk',
  false,
  15,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'spaghetti',
  300,
  'g',
  false,
  16,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  'riven parmesan eller grana padano',
  NULL,
  NULL,
  false,
  17,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  1,
  'Skala, dela och skiva löken. Skala och finhacka vitlöken. Ansa och skär champinjonerna i fyra delar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  2,
  'Häll kikärtorna i ett durkslag, spola dem i kallt vatten och låt rinna av.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  3,
  'Fräs lök, vitlök och svamp i oljan i en stor kastrull på medelhög värme. Tillsätt övriga ingredienser inklusive spaghettin (okokt). Sätt på locket och låt koka upp.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  4,
  'Rör runt och låt koka på medelvärme ca 15 minuter, eller tills pastan är klar. Rör då och då.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  20,
  5,
  'Till servering: Strö över riven eller hyvlad ost vid servering.',
  now()
);

-- recipe_id: 21
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'olivolja, till stekning',
  NULL,
  NULL,
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'gul lök, finhackad',
  1,
  NULL,
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'vitlöksklyftor, finhackade',
  4,
  NULL,
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'röd chili, hackad',
  0.5,
  NULL,
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'tomatpuré',
  0.5,
  'dl',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'frp krossade tomater',
  1,
  NULL,
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'frp salsiccia',
  1,
  NULL,
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'frp mascarpone',
  0.5,
  NULL,
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'salt',
  NULL,
  NULL,
  false,
  9,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'nymalensvartpeppar',
  NULL,
  NULL,
  false,
  10,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'pastavatten',
  1,
  'dl',
  false,
  11,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'frp pasta',
  1,
  NULL,
  false,
  12,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'färskbladpersilja, hackad',
  NULL,
  NULL,
  false,
  13,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  21,
  'parmigiano reggiano, riven',
  NULL,
  NULL,
  false,
  14,
  now()
);

-- recipe_id: 22
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'ök',
  1,
  'l',
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'potatisar (ca 300 g)',
  3,
  NULL,
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'broccoli',
  250,
  'g',
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'grönsaksbuljong (vatten och grönsaksfond eller tärningar)',
  9,
  'dl',
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'matlagningsgrädde',
  2.5,
  'dl',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'salt',
  NULL,
  NULL,
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'peppar',
  NULL,
  NULL,
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'bröd',
  NULL,
  NULL,
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  'kräftstjärtar eller räkor',
  NULL,
  NULL,
  false,
  9,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  1,
  'Skala och skiva lök och potatis. Skär hela broccolin i bitar, även stammen.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  2,
  'Koka upp buljongen och lägg i lök, potatis och broccoli. Koka upp och låt det koka i ca 10 minuter eller tills grönsakerna är mjuka. Mixa soppan med en stavmixer eller i en matberedare.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  3,
  'Häll tillbaka soppan i kastrullen, tillsätt matlagningsgrädde, koka upp och smaka av med salt och peppar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  22,
  4,
  'Till servering: Servera soppan med bröd och kräftstjärtar.',
  now()
);

-- recipe_id: 24
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'kycklingfiléer',
  600,
  'g',
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'olivolja till stekning',
  1,
  'msk',
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'salt',
  NULL,
  NULL,
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'peppar',
  NULL,
  NULL,
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  '1/2 tsk chilipulver',
  1,
  NULL,
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'pressade vitlöksklyftor',
  2,
  NULL,
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'olivolja',
  2,
  'msk',
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'gräddfil',
  1.5,
  'dl',
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'flytande honung',
  2,
  'msk',
  false,
  9,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'fetaost',
  150,
  'g',
  false,
  10,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'tomater',
  4,
  NULL,
  false,
  11,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'rödlök',
  1,
  NULL,
  false,
  12,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'salladsmix',
  65,
  'g',
  false,
  13,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  'stora tortillabröd',
  4,
  NULL,
  false,
  14,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  1,
  'Strimla och salta kycklingfiléerna.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  2,
  'Marinad: Blanda ingredienserna till marinaden. Blanda i kycklingstrimlorna. Låt marinera i rumstemperatur 5-10 minuter.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  3,
  'Fetacrème: Blanda gräddfil och honung. Smula ner fetaosten och rör om. Smaka av med salt och peppar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  4,
  'Till servering: Skär tomaterna i bitar. Skala och skiva löken. Blanda tomater, lök och sallatsblad i en skål.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  5,
  'Stek kycklingen i oljan på medelvärme tills den är genomstekt 5-10 minuter, rör om då och då. Smaka av med salt och peppar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  24,
  6,
  'Låt var och en göra sin egen wrap av brödet, salladen, kycklingen och crèmen.',
  now()
);

-- recipe_id: 25
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'gul lök',
  1,
  NULL,
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'potatisar',
  4,
  NULL,
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'paprika',
  1,
  NULL,
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'olja',
  2,
  'msk',
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'köttfärs gärna ICAs nötfärs 12% eller hushållsfärs (ärt- och nötfärs)',
  500,
  'g',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'vatten',
  6,
  'dl',
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'köttbuljongtärning',
  1,
  NULL,
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'krossade tomater',
  500,
  'g',
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'malen kummin',
  2,
  'tsk',
  false,
  9,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'salt',
  NULL,
  NULL,
  false,
  10,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'peppar',
  NULL,
  NULL,
  false,
  11,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'gräddfil',
  NULL,
  NULL,
  false,
  12,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  'ev varmt vitlöksbröd',
  NULL,
  NULL,
  false,
  13,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  1,
  'Skala lök och potatis. Dela och kärna ur paprikan. Skär i tärningar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  2,
  'Fräs grönsaker, potatis och köttfärs i oljan i en gryta eller kastrull.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  3,
  'Tillsätt vatten, köttbuljongtärning, krossade tomater och kummin. Koka sakta ca 10 minuter. Smaksätt med salt och peppar.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  25,
  4,
  'Till servering: Servera soppan med gräddfil och gärna varmt vitlöksbröd.',
  now()
);

-- recipe_id: 27
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'port ris eller havreris',
  4,
  NULL,
  false,
  1,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'gul lök eller schalottenlök',
  1,
  NULL,
  false,
  2,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'vitlöksklyftor',
  2,
  NULL,
  false,
  3,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'tomater',
  2,
  NULL,
  false,
  4,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'riven ingefära',
  2,
  'msk',
  false,
  5,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'olivolja',
  3,
  'msk',
  false,
  6,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'tomatpuré',
  2,
  'msk',
  false,
  7,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'garam masala',
  1,
  'msk',
  false,
  8,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'krossade tomater',
  390,
  'g',
  false,
  9,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'vatten',
  1,
  'dl',
  false,
  10,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'vispgrädde',
  2,
  'dl',
  false,
  11,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'grönsaksbuljongtärning',
  1,
  NULL,
  false,
  12,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'färsk spenat',
  200,
  'g',
  false,
  13,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'halloumi eller grillost',
  400,
  'g',
  false,
  14,
  now()
);
INSERT INTO public.recipe_ingredients
(id, user_id, recipe_id, name, amount, unit, optional, sort_order, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  'salt',
  2,
  'krm',
  false,
  15,
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  1,
  'Koka riset enligt anvisningen på förpackningen.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  2,
  'Skala lök och vitlök. Skär gula löken och tomaterna i klyftor. Skiva vitlöken. Skala och riv ingefäran fint på ett rivjärn.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  3,
  'Hetta upp hälften av olivoljan i en stekgryta eller kastrull. Fräs lök, vitlök, ingefära, tomatpuré och garam masala 3-4 minuter.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  4,
  'Tillsätt tomater, krossade tomater, vatten, grädde och smulad buljongtärning. Låt sjuda 6-7 minuter. Vänd ner spenaten.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  5,
  'Skär osten i tärningar och stek dem gyllene i resten av olivoljan i en stekpanna.',
  now()
);
INSERT INTO public.recipe_steps
(id, user_id, recipe_id, step_order, text, created_at)
VALUES
(
  gen_random_uuid(),
  'ea906947-eaa4-495e-a455-7cd081b3a8c8',
  27,
  6,
  'Blanda ner osten i grytan och smaka av med salt. Servera med ris.',
  now()
);
